### PR TITLE
Methods and other config that I have Always wanted.

### PR DESCRIPTION
**Pull request by nolanbconaway**
I wrote up an essentially identical class over the last couple of nights. I'd rather have One months package, and the class I wrote implements a superset of the methods in `Month`.

This PR contains those methods. I tested them and its all good. 

I am not super certain about conflicts for python 2.6/2.7 compatibility because I live in python 3. But I didn't use anything that was _aggressively_ python 3.

While I was at it, I edited the  docs and added an API documentation page.

### CODE REVIEW

**Comment by nolanbconaway** [comment]
OK I fixed it for 2.7 but 2.6 fails due to the way the `__init__` unit test was written.

**Comment by nolanbconaway** [comment]
😌

**Comment by kstark** [comment]
Hey! Thanks for the contribution @nolanbconaway - as you can probably tell, this library's been pretty much untouched for a few years. If you give me a day or two I'll review your PR and try to get these changes in; as long as backwards compatibility isn't broken, it should be fine :)

**Comment by nolanbconaway** [comment]
@kstark friendly reminder about this PR!

**Comment by nolanbconaway** [comment]
_gentle nudge_

**Comment by nolanbconaway** [comment]
_casual boop_

**Pull request merged**
